name: Test React App
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v4
      - name: Install dependecies
        run: npm ci
      - name: Test app
        run: npm run test
  print:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Print to console
        run: echo Test is ok!
