name: Publish Workflow / Setup
description: It setting up the repository environment for publish

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'yarn'

    - name: Install dependencies
      run: YARN_ENABLE_SCRIPTS=false yarn install
      shell: bash

    - name: Set Git credentials
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Action"
      shell: bash
