name: Build React App
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v4
      - name: Install dependecies
        run: npm ci
      - name: Build app
        run: npm run build
      - name: Upload artifcat
        uses: actions/upload-artifact@v4
        with:
          path: build
          name: build-files
