name: Print Pull Request
on:
  workflow_dispatch:
  pull_request:
    types: [opened, closed, edited, reopened]
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print event
        run: echo "${{ toJson(github.event) }}"
