name: Checkout PRs and Issues

on:
  workflow_dispatch:
jobs:
  get-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
      with:
        # result-encoding: string
        # retries: 3
        # retry-exempt-status-codes: 400,401
        script: console.log(github.rest)