name: Checkout PRs and Issues
on:
  workflow_dispatch:
jobs:
  get-issues:
    runs-on: ubuntu-latest
    steps:
      - name: View github rest
        uses: actions/github-script@v7
        id: get-issues
        with:
          script: |
            const issuesList = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })

            for (const issue of issuesList) {
              const issueComments = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
              });
              console.log(issueEvents)
            }
