name: Checkout PRs and Issues
on:
  workflow_dispatch:
jobs:
  get-prs:
    runs-on: ubuntu-latest
    steps:
      - name: View github rest
        uses: actions/github-script@v7
        with:
          script: |
            const issuesList = github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })

            console.log(issuesList)
