name: Checkout PRs and Issues
on:
  workflow_dispatch:
jobs:
  get-issues:
    runs-on: ubuntu-latest
    steps:
      - name: View github rest
        uses: actions/github-script@v7
        id: get-issues
        with:
          script: |
            const issuesList = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })

            if (issuesList.data && issuesList.status === 200) {
              for (const issue of issuesList.data) {
                if (issue.pull_request) {
                  const pullComments = await github.rest.pulls.listReviewComments({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: issue.number,
                  });
                } else {
                  const issueComments = await github.rest.issues.listComments({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issue.number,
                  });
                  console.log(issueComments);
                  console.log(issueComments.data.length);

                  if (issueComments.data.length) {
                    const lastComment = await github.rest.issues.getComment({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      comment_id: issueComments.data[issueComments.data.length - 1].id,
                    });
                    console.log(lastComment);
                  }
                }
              }
            }
