name: Checkout PRs and Issues
on:
  workflow_dispatch:
jobs:
  get-issues:
    runs-on: ubuntu-latest
    steps:
      - name: View github rest
        uses: actions/github-script@v7
        id: get-issues
        with:
          script: |
            const issuesList = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })

            console.log(issuesList)
