name: Set label for pull requests
on:
  workflow_dispatch:
jobs:
  set-label-for-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Make gh script
        uses: actions/github-script@v7
        with:
          script: |
            const issuesList = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            if (issuesList.data && issuesList.status === 200) {
              for (const issue of issuesList.data) {
                if (issue.pull_request && !issue.labels.length) {
                  await github.rest.issues.addLabels({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issue.number,
                    labels: ['bug']
                  });
                }
              }
            }
