name: Set label for issues and pull request
on:
  workflow_dispatch:
# on:
#   schedule:
#     - cron: '0 11 * * 1-5'

jobs:
  set-label-for-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Set label for pull requests and issues
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issuesList = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            if (issuesList.data && issuesList.status === 200) {
              for (const issue of issuesList.data) {
                const createdDelta = (new Date() - new Date(issue.created_at)) / (1000 * 60 * 60 * 24)
                console.log('issue', issue);
                console.log('createdDelta', createdDelta);

                if (!issue.labels.length) {
                  if (!issue.labels.length && (
                    (!issue.pull_request && createdDelta > 2) || (issue.pull_request && createdDelta > 7)
                  )) {
                    await github.rest.issues.addLabels({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      issue_number: issue.number,
                      labels: ['bug']
                    });
                  }
                }
              }
            }

