name: Set label for pull requests
on:
  workflow_dispatch:
jobs:
  get-issues:
    runs-on: ubuntu-latest
    steps:
      - name: View github rest
        uses: actions/github-script@v7
        id: get-prs
        with:
          script: |
            const issuesList = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            console.log('issuesList', issuesList);
            if (issuesList.data && issuesList.status === 200) {
              for (const issue of issuesList.data) {
                if (issue.pull_request && !issue.labels.length) {
                  await github.rest.issues.setLabels({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issue.number,
                    labels: ["bug"]
                  });
                }
              }
            }
