name: Set label for issues and pull request
on:
  workflow_dispatch:
# on:
#   schedule:
#     - cron: '0 11 * * 1-5'
jobs:
  set-label-for-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Set label for pull requests and issues
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issuesList = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            if (issuesList.data && issuesList.status === 200) {
              for (const issue of issuesList.data) {
                console.log('issue', issue);
                if (!issue.pull_request && !issue.labels.length) {
                  await github.rest.issues.addLabels({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issue.number,
                    labels: ['bug']
                  });
                }
              }
            }

